# -*- coding: utf-8 -*-
"""Metnum_Klp 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EomJO97HySckVqw8Tg8zsSBQxI9Jti_U
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import CubicSpline

# Konfigurasi halaman
st.set_page_config(
    page_title="Interpolasi Cubic Spline",
    page_icon="🌸",
    layout="centered"
)

# CSS custom tema pink
pink_css = """
<style>
body {
    background-color: #ffe6f2;
}
.block-container {
    padding-top: 2rem;
    background-color: #fff0f6;
    border-radius: 15px;
    padding: 20px;
    box-shadow: 0px 0px 10px rgba(255, 105, 180, 0.3);
}
h1 {
    color: #ff69b4 !important;
}
label, .stTextInput label, .stNumberInput label {
    color: #c2185b !important;
    font-weight: bold;
}
div.stButton > button {
    background-color: #ff8ec7;
    color: white;
    border-radius: 10px;
    padding: 10px 20px;
    border: none;
    font-weight: bold;
}
div.stButton > button:hover {
    background-color: #ff5fad;
    color: white;
}
.stTextInput > div > div > input,
.stNumberInput > div > div > input {
    background-color: #fff5fb !important;
    border-radius: 8px;
    border: 1px solid #ffb7dd !important;
}
.footer {
    text-align:center;
    color:#c94f7c;
    margin-top:20px;
}
</style>
"""
st.markdown(pink_css, unsafe_allow_html=True)

# HEADER
st.markdown(
    """
    <div style="text-align:center;">
        <h1>🌸 Interpolasi Cubic Spline 🌸</h1>
        <p style="font-size:18px; color:#c2185b;">
            Haii! Selamat datang di website interpolasi paling cute 💗<br>
            Masukkan nama variabel dan data X & Y kamu yaa ✨
        </p>
    </div>
    """,
    unsafe_allow_html=True
)

# INPUT
st.subheader("💗 Masukkan Data Anda")

# Variabel X
x_name = st.text_input("🧷 Nama Variabel X", placeholder="contoh: Hari")
x_str  = st.text_input("✨ Data X (pisahkan dengan koma)", placeholder="contoh: 1, 2, 5, 7, 10")

# Variabel Y
y_name = st.text_input("🧷 Nama Variabel Y", placeholder="contoh: Tinggi Jagung (cm)")
y_str  = st.text_input("✨ Data Y (pisahkan dengan koma)", placeholder="contoh: 3, 6, 8, 11, 15")

# Prediksi
x_pred = st.number_input("🔍 Nilai X yang ingin diprediksi", value=None, placeholder="Masukkan angka")

# PROSES
if st.button("💖 Hitung Interpolasi"):
    if (
        x_name.strip() == "" or y_name.strip() == "" or
        x_str.strip() == "" or y_str.strip() == "" or
        x_pred is None
    ):
        st.error("❌ Semua input wajib diisi yaa 💗")
        st.stop()

    try:
        x = np.array([float(i) for i in x_str.split(",")])
        y = np.array([float(i) for i in y_str.split(",")])
    except:
        st.error("❌ Data X dan Y harus berupa angka dan dipisah koma ✨")
        st.stop()

    if len(x) != len(y):
        st.error("❌ Jumlah data X dan Y harus sama 💕")
        st.stop()

    if len(x) < 3:
        st.error("❌ Minimal 3 titik data diperlukan untuk cubic spline 🌸")
        st.stop()

    idx = np.argsort(x)
    x = x[idx]
    y = y[idx]

    if not (x.min() <= x_pred <= x.max()):
        st.error(f"❌ Nilai X prediksi harus di antara {x.min()} dan {x.max()} 💗")
        st.stop()

    spline = CubicSpline(x, y, bc_type="natural")
    y_pred = float(spline(x_pred))

    st.success(f"💗 Hasil Prediksi: {y_name} = {y_pred:.4f}")

    # PLOT
    xx = np.linspace(x.min(), x.max(), 300)
    yy = spline(xx)

    fig, ax = plt.subplots(figsize=(7,4))
    ax.plot(xx, yy, linewidth=2, color="#ff5fa2", label="Kurva Cubic Spline")
    ax.scatter(x, y, color="#c2185b", label="Data Asli")
    ax.scatter(x_pred, y_pred, color="#007bff", s=80,
               label=f"Prediksi ({x_pred})")

    ax.set_xlabel(x_name, fontsize=11, color="#c2185b")
    ax.set_ylabel(y_name, fontsize=11, color="#c2185b")

    ax.grid(True, alpha=0.3)
    ax.legend()
    st.pyplot(fig)

    # PENUTUP
    st.markdown(
        """
        <div style="text-align:center; font-size:17px; color:#d63384; margin-top:20px;">
            Terima kasih sudah mampir 💗<br>
            Semoga hasil interpolasimu memuaskan 🎀
        </div>
        """,
        unsafe_allow_html=True
    )

# FOOTER
st.markdown(
    """
    <p class="footer">Dibuat oleh Bunga, Aira dan Uti 💗</p>
    """,
    unsafe_allow_html=True
)